### ISSUE TITLE
Update to gcc 7.3.1 for stack clash protection

### ISSUE THREAD

**Issue by xerus** [negativo17/cuda-gcc#3]
Hi, I have troubles compiling with cuda-gcc on Fedora 29 because it lacks stack clash protection support
```
cc1plus: error: unrecognized command line option ‘-fstack-clash-protection’
cc1plus: error: unrecognized command line option ‘-fcf-protection’
cc1plus: error: unrecognized command line option ‘-fstack-clash-protection’
cc1plus: error: unrecognized command line option ‘-fcf-protection’
```
Package info:
```
Name        : cuda-gcc
Version     : 7.3.0
Release     : 1.fc29
Architecture: x86_64
Install Date: Fri 23 Nov 2018 04:41:03 PM CET
Group       : Unspecified
Size        : 57950721
License     : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Signature   : DSA/SHA1, Tue 28 Aug 2018 01:51:30 PM CEST, Key ID 14386362f90c0e97
Source RPM  : cuda-gcc-7.3.0-1.fc29.src.rpm
Build Date  : Tue 28 Aug 2018 11:05:17 AM CEST
Build Host  : hooloovoo.localdomain
Relocations : (not relocatable)
URL         : http://gcc.gnu.org
Summary     : GNU Compiler Collection CUDA compatibility package
Description :
The cuda-gcc package contains a CUDA supported version of the GNU Compiler
Collection.
```

RH bugzilla for fedora backporting hardening features: https://bugzilla.redhat.com/show_bug.cgi?id=1512529

**Comment by scaronni** [comment]
There is no release 7.3.1:

ftp://ftp.mpi-sb.mpg.de/pub/gnu/mirror/gcc.gnu.org/pub/gcc/releases/

Unless you mean the 7 snapshot which was included in Fedora 27:

https://koji.fedoraproject.org/koji/buildinfo?buildID=1052992

I'll see what I can do. For now just do not pass those:

https://github.com/negativo17/ccminer/blob/master/ccminer.spec#L3-L9

**Comment by xerus** [comment]
yes, I meant that. Thanks for the advice.

**Comment by scaronni** [comment]
New builds based on the 7.3.1 snapshot available soon.
